# Generated by Django 3.2.10 on 2022-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
    ]
